import { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {Character, GetCharactersResults} from '../types'

const Home: NextPage<{characters: Character[]}> = ({characters})=> {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {
      characters.map((character)=>{
        return <li key={character.id}>{character.name}</li>
      })}
    </div>
  )
}

export const getStaticProps:GetStaticProps = async(context) =>{
      const res = await fetch("https://rickandmortyapi.com/api/character")
      const { results }: GetCharactersResults = await res.json();
      
      return {
        props:{
        characthers:results
      }}
}


export default Home;
